apiVersion: v1
kind: Service
metadata:
  name: geminiservice
  namespace: quanbuy
  labels:
    app: geminiservice
spec:
  type: ClusterIP
  selector:
    app: geminiservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
