apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: agentic-ai-phase1

resources:
- mcp-server.yaml
- shopping-agent.yaml

commonLabels:
  version: v1.0.0
  phase: phase1

images:
- name: gcr.io/PROJECT_ID/mcp-server
  newTag: latest
- name: gcr.io/PROJECT_ID/gemini-shopping-agent  
  newTag: latest

configMapGenerator:
- name: agentic-ai-config
  literals:
  - MCP_SERVER_URL=http://mcp-server:8080
  - AGENT_VERSION=1.0.0
  - LOG_LEVEL=INFO